// Auto-generated by gostd2joker at (omitted for testing), do not edit!!

package smtp

import (
	. "github.com/candid82/joker/core"
)

// func cRAMMD5Auth(username string, secret string) Object {
// 	return smtp.CRAMMD5Auth(username, secret)
// }

// func dial(addr string) Object {
// 	res1, res2 := smtp.Dial(addr)
// 	res := EmptyVector
// 	map1 := EmptyArrayMap()
// 	map1.Add(MakeKeyword("Text"), (*(*res1).Text))
// 	res = res.Conjoin(map1)
// 	res = res.Conjoin(func () Object { if (res2) == nil { return NIL } else { return MakeString(res2.Error()) } }())
// 	return res
// }

// func newClient(conn ABEND882(unrecognized Expr type *ast.SelectorExpr at: tests/big/src/net/smtp/smtp.go:62:21), host string) Object {
// 	res1, res2 := smtp.NewClient(conn, host)
// 	res := EmptyVector
// 	map1 := EmptyArrayMap()
// 	map1.Add(MakeKeyword("Text"), (*(*res1).Text))
// 	res = res.Conjoin(map1)
// 	res = res.Conjoin(func () Object { if (res2) == nil { return NIL } else { return MakeString(res2.Error()) } }())
// 	return res
// }

// func plainAuth(identity string, username string, password string, host string) Object {
// 	return smtp.PlainAuth(identity, username, password, host)
// }
