// Auto-generated by gostd2joker at (omitted for testing), do not edit!!

package rpc

import (
	"net/rpc"
	. "github.com/candid82/joker/core"
)

// func accept(lis ABEND882(unrecognized Expr type *ast.SelectorExpr at: tests/big/src/net/rpc/server.go:692:17)) Object {
// 	rpc.Accept(lis)
// 	...ABEND675: TODO...
// }

func dial(network string, address string) Object {
	res1, res2 := rpc.Dial(network, address)
	res := EmptyVector
	res = res.Conjoin(NIL)
	res = res.Conjoin(func () Object { if (res2) == nil { return NIL } else { return MakeError(res2) } }())
	return res
}

func dialHTTP(network string, address string) Object {
	res1, res2 := rpc.DialHTTP(network, address)
	res := EmptyVector
	res = res.Conjoin(NIL)
	res = res.Conjoin(func () Object { if (res2) == nil { return NIL } else { return MakeError(res2) } }())
	return res
}

func dialHTTPPath(network string, address string, path string) Object {
	res1, res2 := rpc.DialHTTPPath(network, address, path)
	res := EmptyVector
	res = res.Conjoin(NIL)
	res = res.Conjoin(func () Object { if (res2) == nil { return NIL } else { return MakeError(res2) } }())
	return res
}

// func handleHTTP() Object {
// 	rpc.HandleHTTP()
// 	...ABEND675: TODO...
// }

// func newClient(conn ABEND882(unrecognized Expr type *ast.SelectorExpr at: tests/big/src/net/rpc/client.go:193:21)) Object {
// 	return rpc.NewClient(conn)
// 	ABEND124(no public information returned)
// }

// func newClientWithCodec(codec ABEND884(unrecognized type ClientCodec at: tests/big/src/net/rpc/client.go:201:31)) Object {
// 	return rpc.NewClientWithCodec(codec)
// 	ABEND124(no public information returned)
// }

// func newServer() Object {
// 	return rpc.NewServer()
// 	ABEND124(no public information returned)
// }

// func serveCodec(codec ABEND884(unrecognized type ServerCodec at: tests/big/src/net/rpc/server.go:679:23)) Object {
// 	rpc.ServeCodec(codec)
// 	...ABEND675: TODO...
// }

// func serveConn(conn ABEND882(unrecognized Expr type *ast.SelectorExpr at: tests/big/src/net/rpc/server.go:673:21)) Object {
// 	rpc.ServeConn(conn)
// 	...ABEND675: TODO...
// }
