// Auto-generated by gostd2joker at (omitted for testing), do not edit!!

package rpc

import (
	_rpc "net/rpc"
	. "github.com/candid82/joker/core"
)

// func accept(lis ABEND882(unrecognized Expr type *ast.SelectorExpr at: tests\big\src\net\rpc\server.go:692:17)) Object {
// 	_rpc.Accept(lis)
// 	...ABEND675: TODO...
// }

func dial(network string, address string) Object {
	_, _res2 := _rpc.Dial(network, address)
	_res := EmptyVector
	_res = _res.Conjoin(NIL)
	_res = _res.Conjoin(func () Object { if (_res2) == nil { return NIL } else { return MakeError(_res2) } }())
	return _res
}

func dialHTTP(network string, address string) Object {
	_, _res2 := _rpc.DialHTTP(network, address)
	_res := EmptyVector
	_res = _res.Conjoin(NIL)
	_res = _res.Conjoin(func () Object { if (_res2) == nil { return NIL } else { return MakeError(_res2) } }())
	return _res
}

func dialHTTPPath(network string, address string, path string) Object {
	_, _res2 := _rpc.DialHTTPPath(network, address, path)
	_res := EmptyVector
	_res = _res.Conjoin(NIL)
	_res = _res.Conjoin(func () Object { if (_res2) == nil { return NIL } else { return MakeError(_res2) } }())
	return _res
}

// func handleHTTP() Object {
// 	_rpc.HandleHTTP()
// 	...ABEND675: TODO...
// }

// func newClient(conn ABEND882(unrecognized Expr type *ast.SelectorExpr at: tests\big\src\net\rpc\client.go:193:21)) Object {
// 	return _rpc.NewClient(conn)
// 	ABEND124(no public information returned)
// }

// func newClientWithCodec(codec ABEND884(unrecognized type ClientCodec at: tests\big\src\net\rpc\client.go:201:31)) Object {
// 	return _rpc.NewClientWithCodec(codec)
// 	ABEND124(no public information returned)
// }

// func newServer() Object {
// 	return _rpc.NewServer()
// 	ABEND124(no public information returned)
// }

// func serveCodec(codec ABEND884(unrecognized type ServerCodec at: tests\big\src\net\rpc\server.go:679:23)) Object {
// 	_rpc.ServeCodec(codec)
// 	...ABEND675: TODO...
// }

// func serveConn(conn ABEND882(unrecognized Expr type *ast.SelectorExpr at: tests\big\src\net\rpc\server.go:673:21)) Object {
// 	_rpc.ServeConn(conn)
// 	...ABEND675: TODO...
// }
