// Auto-generated by gostd2joker at (omitted for testing), do not edit!!

package cookiejar

import (
)

// func new(o ABEND882(unrecognized Expr type *ast.StarExpr at: tests/big/src/net/http/cookiejar/jar.go:77:12)) Object {
// 	_, _res2 := _cookiejar.New(o)
// 	_res := EmptyVector
// 	_res = _res.Conjoin(NIL)
// 	_res = _res.Conjoin(func () Object { if (_res2) == nil { return NIL } else { return MakeError(_res2) } }())
// 	return _res
// }
