// Auto-generated by gostd2joker at (omitted for testing), do not edit!!

package cookiejar

import (
	. "github.com/candid82/joker/core"
)

// func new(o ABEND882(unrecognized Expr type *ast.StarExpr at: tests/big/src/net/http/cookiejar/jar.go:77:12)) Object {
// 	_, res2 := cookiejar.New(o)
// 	res := EmptyVector
// 	res = res.Conjoin(NIL)
// 	res = res.Conjoin(func () Object { if (res2) == nil { return NIL } else { return MakeError(res2) } }())
// 	return res
// }
