// Auto-generated by gostd2joker at (omitted for testing), do not edit!!

package httptrace

import (
)

// func contextClientTrace(ctx ABEND882(unrecognized Expr type *ast.SelectorExpr at: tests/big/src/net/http/httptrace/trace.go:24:29)) Object {
// 	res := httptrace.ContextClientTrace(ctx)
// 	map1 := EmptyArrayMap()
// 	map1.Add(MakeKeyword("GetConn"), (*res).GetConn)
// 	map1.Add(MakeKeyword("GotConn"), (*res).GotConn)
// 	map1.Add(MakeKeyword("PutIdleConn"), (*res).PutIdleConn)
// 	map1.Add(MakeKeyword("GotFirstResponseByte"), (*res).GotFirstResponseByte)
// 	map1.Add(MakeKeyword("Got100Continue"), (*res).Got100Continue)
// 	map1.Add(MakeKeyword("Got1xxResponse"), (*res).Got1xxResponse)
// 	map1.Add(MakeKeyword("DNSStart"), (*res).DNSStart)
// 	map1.Add(MakeKeyword("DNSDone"), (*res).DNSDone)
// 	map1.Add(MakeKeyword("ConnectStart"), (*res).ConnectStart)
// 	map1.Add(MakeKeyword("ConnectDone"), (*res).ConnectDone)
// 	map1.Add(MakeKeyword("TLSHandshakeStart"), (*res).TLSHandshakeStart)
// 	map1.Add(MakeKeyword("TLSHandshakeDone"), (*res).TLSHandshakeDone)
// 	map1.Add(MakeKeyword("WroteHeaderField"), (*res).WroteHeaderField)
// 	map1.Add(MakeKeyword("WroteHeaders"), (*res).WroteHeaders)
// 	map1.Add(MakeKeyword("Wait100Continue"), (*res).Wait100Continue)
// 	map1.Add(MakeKeyword("WroteRequest"), (*res).WroteRequest)
// 	return map1
// }

// func withClientTrace(ctx ABEND882(unrecognized Expr type *ast.SelectorExpr at: tests/big/src/net/http/httptrace/trace.go:34:26), trace ABEND882(unrecognized Expr type *ast.StarExpr at: tests/big/src/net/http/httptrace/trace.go:34:49)) Object {
// 	return httptrace.WithClientTrace(ctx, trace)
// }
