// Auto-generated by gostd2joker at (omitted for testing), do not edit!!

package pprof

import (
)

// func cmdline(w ABEND882(unrecognized Expr type *ast.SelectorExpr at: tests/big/src/net/http/pprof/pprof.go:83:16), r ABEND882(unrecognized Expr type *ast.StarExpr at: tests/big/src/net/http/pprof/pprof.go:83:39)) Object {
// 	_pprof.Cmdline(w, r)
// 	...ABEND675: TODO...
// }

// func handler(name string) Object {
// 	return _pprof.Handler(name)
// }

// func index(w ABEND882(unrecognized Expr type *ast.SelectorExpr at: tests/big/src/net/http/pprof/pprof.go:264:14), r ABEND882(unrecognized Expr type *ast.StarExpr at: tests/big/src/net/http/pprof/pprof.go:264:37)) Object {
// 	_pprof.Index(w, r)
// 	...ABEND675: TODO...
// }

// func profile(w ABEND882(unrecognized Expr type *ast.SelectorExpr at: tests/big/src/net/http/pprof/pprof.go:116:16), r ABEND882(unrecognized Expr type *ast.StarExpr at: tests/big/src/net/http/pprof/pprof.go:116:39)) Object {
// 	_pprof.Profile(w, r)
// 	...ABEND675: TODO...
// }

// func symbol(w ABEND882(unrecognized Expr type *ast.SelectorExpr at: tests/big/src/net/http/pprof/pprof.go:174:15), r ABEND882(unrecognized Expr type *ast.StarExpr at: tests/big/src/net/http/pprof/pprof.go:174:38)) Object {
// 	_pprof.Symbol(w, r)
// 	...ABEND675: TODO...
// }

// func trace(w ABEND882(unrecognized Expr type *ast.SelectorExpr at: tests/big/src/net/http/pprof/pprof.go:145:14), r ABEND882(unrecognized Expr type *ast.StarExpr at: tests/big/src/net/http/pprof/pprof.go:145:37)) Object {
// 	_pprof.Trace(w, r)
// 	...ABEND675: TODO...
// }
