// Auto-generated by gostd2joker at (omitted for testing), do not edit!!

package jsonrpc

import (
)

// func dial(network string, address string) Object {
// 	_res1, _res2 := _jsonrpc.Dial(network, address)
// 	_res := EmptyVector
// 	_res = _res.Conjoin((*_res1))
// 	_res = _res.Conjoin(func () Object { if (_res2) == nil { return NIL } else { return MakeError(_res2) } }())
// 	return _res
// }

// func newClient(conn ABEND882(unrecognized Expr type *ast.SelectorExpr at: tests/big/src/net/rpc/jsonrpc/client.go:113:21)) Object {
// 	return _jsonrpc.NewClient(conn)
// }

// func newClientCodec(conn ABEND882(unrecognized Expr type *ast.SelectorExpr at: tests/big/src/net/rpc/jsonrpc/client.go:37:26)) Object {
// 	return _jsonrpc.NewClientCodec(conn)
// }

// func newServerCodec(conn ABEND882(unrecognized Expr type *ast.SelectorExpr at: tests/big/src/net/rpc/jsonrpc/server.go:37:26)) Object {
// 	return _jsonrpc.NewServerCodec(conn)
// }

// func serveConn(conn ABEND882(unrecognized Expr type *ast.SelectorExpr at: tests/big/src/net/rpc/jsonrpc/server.go:132:21)) Object {
// 	_jsonrpc.ServeConn(conn)
// 	...ABEND675: TODO...
// }
