// Auto-generated by gostd2joker at (omitted for testing), do not edit!!

package cgi

import (
)

// func request() Object {
// 	res1, res2 := cgi.Request()
// 	res := EmptyVector
// 	res = res.Conjoin((*res1))
// 	res = res.Conjoin(func () Object { if (res2) == nil { return NIL } else { return MakeError(res2) } }())
// 	return res
// }

// func requestFromMap(params ABEND882(unrecognized Expr type *ast.MapType at: tests/big/src/net/http/cgi/child.go:52:28)) Object {
// 	res1, res2 := cgi.RequestFromMap(params)
// 	res := EmptyVector
// 	res = res.Conjoin((*res1))
// 	res = res.Conjoin(func () Object { if (res2) == nil { return NIL } else { return MakeError(res2) } }())
// 	return res
// }
