// Auto-generated by gostd2joker at (omitted for testing), do not edit!!

package cgi

import (
)

// func request() Object {
// 	_res1, _res2 := _cgi.Request()
// 	_res := EmptyVector
// 	_res = _res.Conjoin((*_res1))
// 	_res = _res.Conjoin(func () Object { if (_res2) == nil { return NIL } else { return MakeError(_res2) } }())
// 	return _res
// }

// func requestFromMap(params ABEND882(unrecognized Expr type *ast.MapType at: tests/big/src/net/http/cgi/child.go:52:28)) Object {
// 	_res1, _res2 := _cgi.RequestFromMap(params)
// 	_res := EmptyVector
// 	_res = _res.Conjoin((*_res1))
// 	_res = _res.Conjoin(func () Object { if (_res2) == nil { return NIL } else { return MakeError(_res2) } }())
// 	return _res
// }
