// Auto-generated by gostd2joker at (omitted for testing), do not edit!!

package httptest

import (
)

// func newRecorder() Object {
// 	res := _httptest.NewRecorder()
// 	map1 := EmptyArrayMap()
// 	map1.Add(MakeKeyword("Code"), MakeInt(int((*res).Code)))
// 	map1.Add(MakeKeyword("HeaderMap"), (*res).HeaderMap)
// 	map1.Add(MakeKeyword("Body"), (*(*res).Body))
// 	map1.Add(MakeKeyword("Flushed"), MakeBool((*res).Flushed))
// 	return map1
// }

// func newRequest(method string, target string, body ABEND882(unrecognized Expr type *ast.SelectorExpr at: tests/big/src/net/http/httptest/httptest.go:41:45)) Object {
// 	return _httptest.NewRequest(method, target, body)
// }

// func newServer(handler ABEND882(unrecognized Expr type *ast.SelectorExpr at: tests/big/src/net/http/httptest/server.go:80:24)) Object {
// 	res := _httptest.NewServer(handler)
// 	map1 := EmptyArrayMap()
// 	map1.Add(MakeKeyword("URL"), MakeString((*res).URL))
// 	map1.Add(MakeKeyword("Listener"), (*res).Listener)
// 	map1.Add(MakeKeyword("TLS"), (*(*res).TLS))
// 	map1.Add(MakeKeyword("Config"), (*(*res).Config))
// 	return map1
// }

// func newTLSServer(handler ABEND882(unrecognized Expr type *ast.SelectorExpr at: tests/big/src/net/http/httptest/server.go:160:27)) Object {
// 	res := _httptest.NewTLSServer(handler)
// 	map1 := EmptyArrayMap()
// 	map1.Add(MakeKeyword("URL"), MakeString((*res).URL))
// 	map1.Add(MakeKeyword("Listener"), (*res).Listener)
// 	map1.Add(MakeKeyword("TLS"), (*(*res).TLS))
// 	map1.Add(MakeKeyword("Config"), (*(*res).Config))
// 	return map1
// }

// func newUnstartedServer(handler ABEND882(unrecognized Expr type *ast.SelectorExpr at: tests/big/src/net/http/httptest/server.go:92:33)) Object {
// 	res := _httptest.NewUnstartedServer(handler)
// 	map1 := EmptyArrayMap()
// 	map1.Add(MakeKeyword("URL"), MakeString((*res).URL))
// 	map1.Add(MakeKeyword("Listener"), (*res).Listener)
// 	map1.Add(MakeKeyword("TLS"), (*(*res).TLS))
// 	map1.Add(MakeKeyword("Config"), (*(*res).Config))
// 	return map1
// }
